# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RockPaperScissors(object):
    def setupUi(self, RockPaperScissors):
        RockPaperScissors.setObjectName("RockPaperScissors")
        RockPaperScissors.setWindowModality(QtCore.Qt.ApplicationModal)
        RockPaperScissors.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(RockPaperScissors)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QGraphicsView(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(60, 60, 411, 321))
        self.Background.setObjectName("Background")
        self.Rock_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Rock_Button.setGeometry(QtCore.QRect(110, 290, 75, 23))
        self.Rock_Button.setObjectName("Rock_Button")
        self.Paper_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Paper_Button.setGeometry(QtCore.QRect(220, 290, 75, 23))
        self.Paper_Button.setObjectName("Paper_Button")
        self.Scissors_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Scissors_Button.setGeometry(QtCore.QRect(340, 290, 75, 23))
        self.Scissors_Button.setObjectName("Scissors_Button")
        self.Text_Output = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Output.setGeometry(QtCore.QRect(130, 170, 271, 81))
        self.Text_Output.setObjectName("Text_Output")
        self.quitbutton = QtWidgets.QPushButton(self.centralwidget)
        self.quitbutton.setGeometry(QtCore.QRect(220, 340, 75, 23))
        self.quitbutton.setObjectName("quitbutton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 120, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 120, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 80, 141, 31))
        self.label_3.setObjectName("label_3")
        self.compscore = QtWidgets.QTextBrowser(self.centralwidget)
        self.compscore.setGeometry(QtCore.QRect(190, 120, 41, 31))
        self.compscore.setObjectName("compscore")
        self.myscore = QtWidgets.QTextBrowser(self.centralwidget)
        self.myscore.setGeometry(QtCore.QRect(290, 120, 41, 31))
        self.myscore.setObjectName("myscore")
        RockPaperScissors.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RockPaperScissors)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        RockPaperScissors.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RockPaperScissors)
        self.statusbar.setObjectName("statusbar")
        RockPaperScissors.setStatusBar(self.statusbar)

        self.retranslateUi(RockPaperScissors)
        QtCore.QMetaObject.connectSlotsByName(RockPaperScissors)

    def retranslateUi(self, RockPaperScissors):
        _translate = QtCore.QCoreApplication.translate
        RockPaperScissors.setWindowTitle(_translate("RockPaperScissors", "MainWindow"))
        self.Rock_Button.setText(_translate("RockPaperScissors", "Rock"))
        self.Paper_Button.setText(_translate("RockPaperScissors", "Paper"))
        self.Scissors_Button.setText(_translate("RockPaperScissors", "Scissors"))
        self.quitbutton.setText(_translate("RockPaperScissors", "QUIT GAME"))
        self.label.setText(_translate("RockPaperScissors", "Computer Score"))
        self.label_2.setText(_translate("RockPaperScissors", "My Score"))
        self.label_3.setText(_translate("RockPaperScissors", "Rock Paper Scissors Game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RockPaperScissors = QtWidgets.QMainWindow()
    ui = Ui_RockPaperScissors()
    ui.setupUi(RockPaperScissors)
    RockPaperScissors.show()
    sys.exit(app.exec_())
